### ISSUE TITLE
System cannot find the path specified?

### ISSUE THREAD

**Issue by patcat** [networked-aframe/networked-aframe#4]
Hiya!

When trying to install it on my Windows PC, it seems to fail with the error "System cannot find the path specified". It seems like maybe it's a WebRTC issue? I've updated node and npm to the latest versions but it's still not happy!

It fails on this command - **npm install && npm run easyrtc-install**

The log looks like so:

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Programs\\nodejs\\node.exe',
1 verbose cli   'D:\\Programs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'easyrtc-install' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose run-script [ 'preeasyrtc-install',
4 verbose run-script   'easyrtc-install',
4 verbose run-script   'posteasyrtc-install' ]
5 info lifecycle networked-aframe@0.1.0~preeasyrtc-install: networked-aframe@0.1.0
6 silly lifecycle networked-aframe@0.1.0~preeasyrtc-install: no script for preeasyrtc-install, continuing
7 info lifecycle networked-aframe@0.1.0~easyrtc-install: networked-aframe@0.1.0
8 verbose lifecycle networked-aframe@0.1.0~easyrtc-install: unsafe-perm in lifecycle true
9 verbose lifecycle networked-aframe@0.1.0~easyrtc-install: PATH: D:\Programs\nodejs\node_modules\npm\bin\node-gyp-bin;D:\lab\networked-aframe\node_modules\.bin;C:\Users\Admin\bin;D:\Programs\Git\mingw64\bin;D:\Programs\Git\usr\local\bin;D:\Programs\Git\usr\bin;D:\Programs\Git\usr\bin;D:\Programs\Git\mingw64\bin;D:\Programs\Git\usr\bin;C:\Users\Admin\bin;C:\Program Files\Oculus\Support\oculus-runtime;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\GtkSharp\2.12\bin;D:\Programs\Git\cmd;D:\Programs\PuTTY;D:\Programs\Android\sdk\platform-tools;D:\Programs\nodejs;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Users\Admin\AppData\Roaming\npm;D:\Programs\Git\usr\bin\vendor_perl;D:\Programs\Git\usr\bin\core_perl
10 verbose lifecycle networked-aframe@0.1.0~easyrtc-install: CWD: D:\lab\networked-aframe
11 silly lifecycle networked-aframe@0.1.0~easyrtc-install: Args: [ '/d /s /c',
11 silly lifecycle   'cd ./node_modules/easyrtc; npm install; cd ../../server; npm install; cd ../' ]
12 silly lifecycle networked-aframe@0.1.0~easyrtc-install: Returned: code: 1  signal: null
13 info lifecycle networked-aframe@0.1.0~easyrtc-install: Failed to exec easyrtc-install script
14 verbose stack Error: networked-aframe@0.1.0 easyrtc-install: `cd ./node_modules/easyrtc; npm install; cd ../../server; npm install; cd ../`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Programs\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Programs\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid networked-aframe@0.1.0
16 verbose cwd D:\lab\networked-aframe
17 error Windows_NT 10.0.14393
18 error argv "D:\\Programs\\nodejs\\node.exe" "D:\\Programs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "easyrtc-install"
19 error node v6.10.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error networked-aframe@0.1.0 easyrtc-install: `cd ./node_modules/easyrtc; npm install; cd ../../server; npm install; cd ../`
22 error Exit status 1
23 error Failed at the networked-aframe@0.1.0 easyrtc-install script 'cd ./node_modules/easyrtc; npm install; cd ../../server; npm install; cd ../'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the networked-aframe package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cd ./node_modules/easyrtc; npm install; cd ../../server; npm install; cd ../
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs networked-aframe
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls networked-aframe
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by haydenjameslee** [comment]
Try running the following commands separately and this will give more info:

(Start in /networked-aframe/)

```sh
cd ./node_modules/easyrtc;
npm install;
cd ../../server;
npm install;
```

**Comment by patcat** [comment]
It looks like the ; at the ends isn't liked by Windows Command Prompt. Running:

`cd ./node_modules/easyrtc;`

ends up with the "The system cannot find the path specified"

But
`cd ./node_modules/easyrtc`
works a-okay.

Or at least... it doesn't error. However, running the framework via `npm start` an going to `http://localhost:8080` leads me to a "Connection refused" page in the browser.

Here's what npm shows when it's running:
`> networked-aframe@0.1.0 start D:\Lab\networked-aframe
> npm run dev


> networked-aframe@0.1.0 dev D:\Lab\networked-aframe
> npm run watch & npm run easyrtc-start


> networked-aframe@0.1.0 watch D:\Lab\networked-aframe
> watchify src/index.js -o server/static/build.js -v

89145 bytes written to server/static/build.js (0.34 seconds) at 11:47:17 PM`

Does it look like anything isn't running or set up properly from that? I wonder if this is a different issue, rather than linked to this one.

**Comment by patcat** [comment]
@haydenjameslee Not sure which update fixed it but I'm not getting this issue after updating to your latest update and testing out the port number changing (it worked before I changed the port number, so totally a-okay out of the box now on PC from the looks of it!)

**Comment by Vamoss** [comment]
This error still happening. It is related to this topic:
https://github.com/npm/npm/issues/4040

**Comment by vincentfretin** [comment]
`npm run easyrtc-install` doesn't exist anymore with open-easyrtc, see https://github.com/networked-aframe/networked-aframe/issues/240#issuecomment-784487989
