### ISSUE TITLE
easyrtc: connection error causes crash

### ISSUE THREAD

**Issue by rrrepos** [networked-aframe/networked-aframe#83]
Hello,

I thought of recording a crash caused by easyrtc. It occurred when the networked-scene was being loaded. I am reproducing the error below. 

```
EasyRTC: [default][pwob0IPhU3GLevUK] Running func 'onGetIceConfig'
/Users/rajnikantrao/Documents/GitHub/hudddle/node/node_modules/easyrtc/lib/easyrtc_public_obj.js:1668
            for (var fieldName in e.app[appName].connection[easyrtcid].field) {
                                                                       ^

TypeError: Cannot read property 'field' of undefined
    at Object.connectionObj.getFields (/Users/rajnikantrao/Documents/GitHub/hudddle/node/node_modules/easyrtc/lib/easyrtc_public_obj.js:1668:72)
    at /Users/rajnikantrao/Documents/GitHub/hudddle/node/node_modules/easyrtc/lib/easyrtc_default_event_listeners.js:1079:27
    at fn (/Users/rajnikantrao/Documents/GitHub/hudddle/node/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/Users/rajnikantrao/Documents/GitHub/hudddle/node/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
```

This is the first time I am facing this error. Not sure if it is related to the earlier issue (#77) reported a few days back.

**Comment by hthetiot** [comment]
Fixed via #175 OpenEasyRTC Migration.
